COMPONENT=BaseStationC
CFLAGS += -DTASKLET_IS_TASK
CFLAGS += -I$(TOSDIR)/lib/printf
# CFLAGS += -DCC2420_NO_ACKNOWLEDGEMENTS
CFLAGS += -DRECEIVE_HISTORY_SIZE=0
DEFAULT_LOCAL_GROUP=0x2A

include $(MAKERULES)

